spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    defer-datasource-initialization: true

jwt_secret: secreto
test2: Testing 50!